// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenFile():Promise<main.FileData>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SaveFileDirect(arg1:string,arg2:string):Promise<void>;
